export const SEARCH_TYPE = "SEARCH_TYPE";
export const LANGUAGE_TYPE = "LANGUAGE_TYPE";

export const FETCH_VI_DATA = "FETCH_VI_DATA";
export const FETCH_EN_DATA = "FETCH_EN_DATA";
export const FETCH_SEARCH_DATA = "FETCH_SEARCH_DATA";
export const FETCH_DETAIL_SENTENCE = "FETCH_DETAIL_SENTENCE";
export const FETCH_SEARCH_STRUCTURE = "FETCH_SEARCH_STRUCTURE";
export const NEXT_PAGE = "NEXT_PAGE";
export const FETCH_STATIS_QUERY = "FETCH_STATIS_QUERY";
export const FETCH_STATIS_SUMARY = "FETCH_STATIS_SUMARY";
export const RESET_LOADING = "RESET_LOADING";
export const SET_ALERT = "SET_ALERT";

export const UPDATE_PAGE_SEARCH = "UPDATE_PAGE_SEARCH";
export const UPDATE_PAGE_HOME = "UPDATE_PAGE_HOME";
export const UPDATE_PAGE_SEARCH_STRUCTURE = "UPDATE_PAGE_SEARCH_STRUCTURE";
export const UPDATE_SEARCH_LIST = "UPDATE_SEARCH_LIST";
export const UPDATE_TOTAL_PAGE_SEARCH = "UPDATE_TOTAL_PAGE_SEARCH";
export const UPDATE_TOTAL_PAGE_HOME = "UPDATE_TOTAL_PAGE_HOME";
export const REFRESH_SEARCH_STRUCTURE = "REFRESH_SEARCH_STRUCTURE";

export const ADD_SINGLE_USER_CORPUS = "ADD_SINGLE_USER_CORPUS";
